### ISSUE TITLE
Account API

### ISSUE THREAD

**Issue by CuriosityChan** [MockingJayWong/FinalProject_SE305#10]
#### 5.1.1 register (GET)
```
获取注册页面
GET /account/register
```
---
```
args: none
```
---
```
return 'register'
```

#### 5.1.2 register (POST)
```
用户注册
POST /account/register
```
---
```
args: 
  （注意需要对参数进行验证，验证通过才创建用户）
    username: String  // 验证用户名有字母数字、下划线构成，长度6-16，唯一性
    password: String   // 长度6-16
    password2: String // 与password一致
    email: String  // 符合邮箱格式，唯一性
    telephone: String  // 11位数字，唯一性
```
---
```
创建用户成功：
return:
{
    status:"success",
    data: {
        url:"xxx"
    }
}

创建用户失败：
return:
{
    status:"fail",
    data: {
        user: {  // 所有未通过验证的错误信息
            username: "用户名格式不正确"， // 或者其他错误信息
            password: "xxx",
            .... 
        }
}
